#!/bin/sh
# delete git history, keep the code
# http://stackoverflow.com/a/26000395

if [ $# -ne 1 ]
then
    echo "usage: `basename "$0"` commit_message"
else
    git checkout --orphan latest_branch
    git add -A
    git commit -am "$1"
    git branch -D main
    git branch -m main
    git push -f origin main
fi
