#!/bin/bash

git submodule foreach git checkout -b temp 

git submodule foreach git checkout master 

git submodule foreach git merge temp 

git submodule foreach git branch -D temp 

git submodule foreach git add . 

git submodule foreach git commit -m 'Om'

git submodule foreach git push
