#!/bin/bash

rofi_command="rofi -theme ~/dotfiles/rofi/themes/screenshot"

# Options
screen=""
area=""
window=""

# Variable passed to rofi
options="$screen\n$area\n"

chosen="$(echo -e "$options" | $rofi_command -p '' -dmenu -selected-row 1)"
case $chosen in
    $screen)
        sleep 1; snap full
        ;;
    $area)
       snap area
        ;;
esac


