#!/bin/bash

if [! $HOME/Pictures/Screenshots] ; then 
mkdir -p $HOME/Pictures/Screenshots 
fi 


$SCREENSHOTS_DIR = $HOME/Pictures/Screenshots
rofi_command="rofi -theme themes/scrotmenu.rasi"


### Options ###
screen="Screen "
area="Area "
window="Window "
# Variable passed to rofi
options="$screen\n$area\n$window"

chosen="$( echo -e "$options" | $rofi_command -dmenu -selected-row 3)"
case $chosen in
    $screen)
        sleep 1; scrot '%T-%F' -e 'mv $f ~/Pictures/Screenshots/'
        ;;
    $area)
        scrot '%T-%F' --line style=dash,width=5 -s -e 'mv $f ~/Pictures/Screenshots/' 
        ;;
    $window)
        sleep 1; scrot -u -e 'mv $f ~/Pictures/Screenshots/'
        ;;
esac

