#!/bin/env bash
temp="temp_"
tempfile=$(echo $temp$file)
for file in $*
do
sed -e "s/#9ABEFF/#0badff/g" $file > $tempfile
mv temp$file $file
echo "Change Callout -5 " 
echo 
 echo $DATE 
 done


for file in $*
do
sed -e "s/#F8C18C/#f0ffaa/g" $file > $tempfile
mv temp$file $file
echo "Change Callout -4 " 
echo 
 echo $DATE 
 done


for file in $*
do
sed -e "s/#FF837D/#ff28a9/g" $file > $tempfile
mv temp$file $file
echo "Change Callout -3"
echo 
 echo $DATE 
 done

for file in $*
do
sed -e "s/#99CDCD/00ffcc/g" $file > $tempfile
mv temp$file $file
echo "Change Callout -2"
echo 
 echo $DATE 
 done
for file in $*
do
sed -e "s/#F9DE81/#f9f871/g" $file > $tempfile
mv temp$file $file
done

