#!/bin/bash
#made by toru
#irc.unixhub.net
  bkf=$'\e[30m';   rf=$'\e[31m';    gf=$'\e[32m'
  yf=$'\e[33m'   bf=$'\e[34m';   mf=$'\e[35m'
  cf=$'\e[36m';    wf=$'\e[37m'

  bkb=$'\e[40m';   rb=$'\e[41m';    gb=$'\e[42m'
  yb=$'\e[43m'   bb=$'\e[44m';   mb=$'\e[45m'
  cb=$'\e[46m';    wb=$'\e[47m'; rst=$'\e[0m'

  ibkf=$'\e[90m';   irf=$'\e[91m';    igf=$'\e[92m'
  iyf=$'\e[93m'   ibf=$'\e[94m';   imf=$'\e[95m'
  icf=$'\e[96m';    iwf=$'\e[97m'

  ibkb=$'\e[100m';   irb=$'\e[101m';    igb=$'\e[102m'
  iyb=$'\e[103m'   ibb=$'\e[104m';   imb=$'\e[105m'
  icb=$'\e[106m';    iwb=$'\e[107m';
 #over all length of mushrooms = 64

# width of terminal
width=$(tput cols)

for ((v=0; v < ($width-64)/3; v++))
do
spaces="$spaces "
done

cat << EOF
${ibkf}   ▄▄█${iwb}▀${rb}▀▀${iwb}▀█${rst}${ibkf}▄${rst}${break}${spaces}    ${ibkf}   ▄▄█${iwb}▀${gb}▀▀${iwb}▀█${rst}${ibkf}▄${rst}${break}${spaces}    ${ibkf}   ▄▄█${iwb}▀${yb}▀▀${iwb}▀█${rst}${ibkf}▄${rst}${break}${spaces}    ${ibkf}   ▄▄█${iwb}▀${bb}▀▀${iwb}▀█${rst}${ibkf}▄${rst}
${ibkf} ▄█${rb}▀${iwf}██▀${rf}██${wf}${rb}▀██${ibkf}▀█${rst}${ibkf}▄${rst}${break}${spaces} ${ibkf} ▄█${gb}▀${iwf}██▀${gf}██${iwf}${gb}▀██${ibkf}▀█${rst}${ibkf}▄${rst}${break}${spaces} ${ibkf} ▄█${yb}▀${iwf}██▀${yf}██${iwf}${yb}▀██${ibkf}▀█${rst}${ibkf}▄${rst}${break}${spaces} ${ibkf} ▄█${bb}▀${iwf}██▀${bf}██${iwf}${bb}▀██${ibkf}▀█${rst}${ibkf}▄${rst}
${ibkf}▄█${iwf}█${rb}▄${rf}██${iwb}▀▀▀▀██▀${iwf}█${rst}${ibkf}█▄${rst}${break}${spaces}${ibkf}▄█${iwf}█${gb}▄${gf}██${iwb}▀▀▀▀██▀${iwf}█${rst}${ibkf}█▄${rst}${break}${spaces}${ibkf}▄█${iwf}█${yb}▄${yf}██${iwb}▀▀▀▀██▀${iwf}█${rst}${ibkf}█▄${rst}${break}${spaces}${ibkf}▄█${iwf}█${bb}▄${bf}██${iwb}▀▀▀▀██▀${iwf}█${rst}${ibkf}█▄${rst}
${ibkf}█${iwf}███${rf}█${iwf}██████${rf}█${iwf}███${ibkf}█${rst}${break}${spaces}${ibkf}█${iwf}███${gf}█${iwf}██████${gf}█${iwf}███${ibkf}█${rst}${break}${spaces}${ibkf}█${iwf}███${yf}█${iwf}██████${yf}█${iwf}███${ibkf}█${rst}${break}${spaces}${ibkf}█${iwf}███${bf}█${iwf}██████${bf}█${iwf}███${ibkf}█${rst}
${ibkf}█${rf}${iwb}▄▄██▄${iwf}████${rf}${iwb}▄██▄▄${ibkf}█${rst}${break}${spaces}${ibkf}█${gf}${iwb}▄▄██▄${iwf}████${gf}${iwb}▄██▄▄${ibkf}█${rst}${break}${spaces}${ibkf}█${yf}${iwb}▄▄██▄${iwf}████${yf}${iwb}▄██▄▄${ibkf}█${rst}${break}${spaces}${ibkf}█${bf}${iwb}▄▄██▄${iwf}████${bf}${iwb}▄██▄▄${ibkf}█${rst}
${ibkf}█${iwb}▄▄█▀▀█▀▀█▀▀█▄▄█${rst}${break}${spaces}${ibkf}█${iwb}▄▄█▀▀█▀▀█▀▀█▄▄█${rst}${break}${spaces}${ibkf}█${iwb}▄▄█▀▀█▀▀█▀▀█▄▄█${rst}${break}${spaces}${ibkf}█${iwb}▄▄█▀▀█▀▀█▀▀█▄▄█${rst}
${ibkf} ▀█${iwf}███${ibkb}▄██▄███${rst}${ibkf}█▀${rst}${break}${spaces} ${ibkf} ▀█${iwf}███${ibkb}▄██▄███${rst}${ibkf}█▀${rst}${break}${spaces} ${ibkf} ▀█${iwf}███${ibkb}▄██▄███${rst}${ibkf}█▀${rst}${break}${spaces} ${ibkf} ▀█${iwf}███${ibkb}▄██▄███${rst}${ibkf}█▀${rst}
${ibkf}  ▀█${iwb}▄▄▄▄▄▄▄▄█${rst}${ibkf}▀${rst}${break}${spaces}  ${ibkf}  ▀█${iwb}▄▄▄▄▄▄▄▄█${rst}${ibkf}▀${rst}${break}${spaces}  ${ibkf}  ▀█${iwb}▄▄▄▄▄▄▄▄█${rst}${ibkf}▀${rst}${break}${spaces}  ${ibkf}  ▀█${iwb}▄▄▄▄▄▄▄▄█${rst}${ibkf}▀${rst}${endofline}
${break}
EOF
