#!/bin/bash
#vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4:
# Tuned Linux
#
# Thomas Leon Highbaugh
#
# Based on work by: Nicolas Brousse & juancarlospaco
#
# Notes :
#   Use this script at your OWN risk. There is no guarantee whatsoever.
#!/usr/bin/env bash
## ANSI Colors (FG & BG)
RED="$(printf '\033[31m')" GREEN="$(printf '\033[32m')" ORANGE="$(printf '\033[33m')" BLUE="$(printf '\033[34m')"
MAGENTA="$(printf '\033[35m')" CYAN="$(printf '\033[36m')" WHITE="$(printf '\033[37m')" BLACK="$(printf '\033[30m')"
REDBG="$(printf '\033[41m')" GREENBG="$(printf '\033[42m')" ORANGEBG="$(printf '\033[43m')" BLUEBG="$(printf '\033[44m')"
MAGENTABG="$(printf '\033[45m')" CYANBG="$(printf '\033[46m')" WHITEBG="$(printf '\033[47m')" BLACKBG="$(printf '\033[40m')"

## Banner
clear
cat <<-_EOF_
	${CYAN}┌─────────────────────────────────────────────────────────────────────────────┐
	│  ${MAGENTA}                                                                           ${CYAN}│
	│  ${MAGENTA} _______                       __   _____   __                             ${CYAN}│
	│  ${MAGENTA}|_     _|.--.--.-----.-----.--|  | |     |_|__|.-----.--.--.--.--.         ${CYAN}│
	│  ${MAGENTA}  |   |  |  |  |     |  -__|  _  | |       |  ||     |  |  |_   _|         ${CYAN}│
	│  ${MAGENTA}  |___|  |_____|__|__|_____|_____| |_______|__||__|__|_____|__.__|         ${CYAN}│
	└─────────────────────────────────────────────────────────────────────────────┘                                                                  
_EOF_

host=$(cat /etc/hostname)




function sysctl() {
echo "${GREEN}" "Update sysctl for $host"

#### Fine tuning network parameters for better perfomance
# Change the following parameters when a high rate of incoming connection requests result in connection failures
echo "100000" > /proc/sys/net/core/netdev_max_backlog
# Size of the listen queue for accepting new TCP connections (default: 128)
echo "4096" > /proc/sys/net/core/somaxconn
# Maximum number of sockets in TIME-WAIT to be held simultaneously (default: 180000)
echo "600000" > /proc/sys/net/ipv4/tcp_max_tw_buckets
# sets the Maximum Socket Receive Buffer for all protocols (in bytes)
echo "16777216" > /proc/sys/net/core/rmem_max
echo "16777216" > /proc/sys/net/core/rmem_default
# sets the Maximum Socket Send Buffer for all protocols (in bytes)
echo "16777216" > /proc/sys/net/core/wmem_max
echo "16777216" > /proc/sys/net/core/wmem_default
# Set Linux autotuning TCP buffer limits
echo "4096 87380 16777216" > /proc/sys/net/ipv4/tcp_rmem
echo "4096 87380 16777216" > /proc/sys/net/ipv4/tcp_wmem

echo "0" > /proc/sys/net/ipv4/tcp_sack
echo "0" > /proc/sys/net/ipv4/tcp_dsack
# By default, TCP saves various connection metrics in the route cache when the connection closes, so that connections established in the near future can use these to set initial conditions. Usually, this increases overall performance, but may sometimes cause performance degradation. If set, TCP will not cache metrics on closing connections.
echo "1" > /proc/sys/net/ipv4/tcp_no_metrics_save
# How many times to retry before killing an alive TCP connection
echo "5" > /proc/sys/net/ipv4/tcp_retries2
# How often to send TCP keepalive packets to keep an connection alive if it is currently unused. This value is only used when keepalive is enabled
echo "120" > /proc/sys/net/ipv4/tcp_keepalive_time
# How long to wait for a reply on each keepalive probe. This value is in other words extremely important when you try to calculate how long time will go before your connection will die a keepalive death. 
echo "30" > /proc/sys/net/ipv4/tcp_keepalive_intvl
# Determines the number of probes before timing out
echo "3" > /proc/sys/net/ipv4/tcp_keepalive_probes
# How long to keep sockets in the state FIN-WAIT-2 if you were the one closing the socket (default: 60)
echo "30" > /proc/sys/net/ipv4/tcp_fin_timeout
# Sometimes, packet reordering in a network can be interpreted as packet loss and hence increasing the value of this parameter should improve performance (default is “3″)
echo "15" > /proc/sys/net/ipv4/tcp_reordering
#
echo "cubic" > /proc/sys/net/ipv4/tcp_congestion_control
# This value varies depending on total memory of the system. Use it wisely in different situations
# echo "262144" > /proc/sys/net/ipv4/tcp_max_orphans

# Disable Core Dumps
echo "0" > /proc/sys/fs/suid_dumpable
# Enable ExecShield
echo "1" > /proc/sys/kernel/exec-shield
echo "1" > /proc/sys/kernel/randomize_va_space
#### Network parameters for better security
# Disable packet forwarding (if this machine is not a router)
echo "0" > /proc/sys/net/ipv4/ip_forward
echo "0" > /proc/sys/net/ipv4/conf/all/send_redirects
echo "0" > /proc/sys/net/ipv4/conf/default/send_redirects
# Enable tcp_syncookies to accept legitimate connections when faced with a SYN flood attack
echo "1" > /proc/sys/net/ipv4/tcp_syncookies
# Turn off to disable IPv4 protocol features which are considered to have few legitimate uses and to be easy to abuse
echo "0" > /proc/sys/net/ipv4/conf/all/accept_source_route
echo "0" > /proc/sys/net/ipv4/conf/default/accept_source_route
echo "0" > /proc/sys/net/ipv4/conf/all/accept_redirects
echo "0" > /proc/sys/net/ipv4/conf/default/accept_redirects
echo "0" > /proc/sys/net/ipv4/conf/all/secure_redirects 
echo "0" > /proc/sys/net/ipv4/conf/default/secure_redirects 
# Log suspicious packets (This should be turned off if the system is suffering from too much logging)
echo "1" > /proc/sys/net/ipv4/conf/all/log_martians
# Protect from ICMP attacks 
echo "1" > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts
# Enable RFC-recommended source validation (should not be used on machines which are routers for very complicated networks
echo "1" > /proc/sys/net/ipv4/conf/all/rp_filter
echo "1" > /proc/sys/net/ipv4/conf/default/rp_filter
# Increase IPv4 port range to accept more connections
echo "5000 65535" > /proc/sys/net/ipv4/ip_local_port_range

# Disable IPV6
echo "1" > /proc/sys/net/ipv6/conf/all/disable_ipv6
echo "1" > /proc/sys/net/ipv6/conf/default/disable_ipv6
# 
#### File system tuning 
# Increase system file descriptor limit
echo "7930900" > /proc/sys/fs/file-max
# Allow for more PIDs
echo "65536" > /proc/sys/kernel/pid_max
# Use up to 95% of RAM (5% free)
echo "5" > /proc/sys/vm/swappiness
#
echo "20" > /proc/sys/vm/dirty_background_ratio
#
echo "25" > /proc/sys/vm/dirty_ratio)

/sbin/sysctl -p /etc/sysctl.conf
echo ${BLUE} "sysctl.conf has been written successfully"

}

function pacman() {
	sudo mkdir -p  /etc/pacman.d/
sudo touch /etc/pacman.d/tuned.conf	
	echo "${GREEN}" "The following prompts will ask you if you would like to eliminate various modules from pacman I am unlikely to use and thus can strip from my system. Consider each carefully, as your needs will undoubtably different from mine own."
    echo "${GREEN}" "Type y to confirm or anything else to deny the removal of the following modules."


read -rp "${BLUE}.PYC Python bytecode cache files: ${WHITE}"  response  
response=${response,,}
case "$response" in 
   [yY])  echo " NoExtract = usr/bin/__pycache__/* " >> /etc/pacman.d/tuned.conf ;;
   ?) echo ${RED} "declined" "${WHITE}";;
esac


read -rp "${BLUE}Non-English Locale translations: ${WHITE}"  response  
response=${response,,}
case "$response" in 
   [yY])  echo " NoExtract = usr/share/locale/* usr/share/X11/locale/* usr/share/i18n/* !*locale*/en*/* !usr/share/i18n/charmaps/UTF-8.gz !usr/share/*locale*/locale.* !usr/share/*locales/en_?? !usr/share/*locales/i18n* !usr/share/*locales/iso* !usr/share/*locales/trans* " >> /etc/pacman.d/tuned.conf ;;
   ?) echo ${RED} "declined" "${WHITE}" ;;
esac

read -rp "${BLUE}Non-English Locales in VIM: ${WHITE}"  response  
response=${response,,}
case "$response" in 
   [yY])  echo " NoExtract =usr/share/vim/vim*/lang/* " >> /etc/pacman.d/tuned.conf ;;
   ?) echo ${RED} "declined" "${WHITE}" ;;
esac


read -rp "${BLUE}PGP Non-English plain-text help local documentation: ${WHITE}"  response  
response=${response,,}
case "$response" in 
   [yY])  echo " NoExtract = usr/share/gnupg/help.*.txt " >> /etc/pacman.d/tuned.conf ;;
   ?) echo ${RED} "declined" "${WHITE}" ;;
esac

read -rp "${BLUE}GTK-Doc HTML help local documentation: ${WHITE}"  response  
response=${response,,}
case "$response" in 
   [yY])  echo " NoExtract = usr/share/gtk-doc/html/* " >> /etc/pacman.d/tuned.conf ;;
   ?) echo ${RED} "declined" "${WHITE}" ;;
esac


read -rp "${BLUE}Google Chrome device drivers like Chromebook ChromeCast Google Nest Google Assistant: ${WHITE}"  response  
response=${response,,}
case "$response" in 
   [yY])  echo " NoExtract = usr/lib/modules/[1-9]*-ARCH/kernel/drivers/platform/chrome* " >> /etc/pacman.d/tuned.conf ;;
   ?) echo ${RED} "declined" "${WHITE}" ;;
esac

read -rp "${BLUE}Non-English plain-text help local documentation: ${WHITE}"  response  
response=${response,,}
case "$response" in 
   [yY])  echo " NoExtract =usr/share/doc/* usr/share/help/* !usr/share/help/en* " >> /etc/pacman.d/tuned.conf ;;
   ?) echo ${RED} "declined" "${WHITE}" ;;
esac



read -rp "${BLUE}  Integrated Services Digital Network ISDN Network router and modem drivers of any kind from 1990 or older: ${WHITE}"  response  
response=${response,,}
case "$response" in 
   [yY])  echo " NoExtract = usr/lib/modules/[1-9]*-ARCH/kernel/drivers/isdn* " >> /etc/pacman.d/tuned.conf ;;
   ?) echo ${RED} "declined" "${WHITE}" ;;
esac


read -rp "${BLUE} BATMAN Network router and modem drivers of any kind: ${WHITE}"  response  
response=${response,,}
case "$response" in 
   [yY])  echo " NoExtract = usr/lib/modules/[1-9]*-ARCH/kernel/net/batman-adv* " >> /etc/pacman.d/tuned.conf ;;
   ?) echo ${RED} "declined" "${WHITE}" ;;
esac

read -rp "${BLUE}  InfraRed IR drivers of any kind like infrared remote controls: ${WHITE}"  response  
response=${response,,}
case "$response" in 
   [yY])  echo " NoExtract = usr/lib/modules/[1-9]*-ARCH/kernel/drivers/net/irda* usr/lib/modules/[1-9]*-ARCH/kernel/net/irda*" >> /etc/pacman.d/tuned.conf ;;
   ?) echo ${RED} "declined" "${WHITE}" ;;
esac

read -rp "${BLUE}  Sun MicroSystems Remote Procedure Call SunRPC for Sun hardware drivers of any kind: ${WHITE}"  response  
response=${response,,}
case "$response" in 
   [yY])  echo " NoExtract =usr/lib/modules/[1-9]*-ARCH/kernel/net/sunrpc* " >> /etc/pacman.d/tuned.conf ;;
   ?) echo ${RED} "declined" "${WHITE}" ;;
esac

read -rp "${BLUE} Parallel port printer port drivers of any kind: ${WHITE}"  response  
response=${response,,}
case "$response" in 
   [yY])  echo " NoExtract =  usr/lib/modules/[1-9]*-ARCH/kernel/drivers/parport* " >> /etc/pacman.d/tuned.conf ;;
   ?) echo ${RED} "declined" "${WHITE}" ;;
esac

read -rp "${BLUE}NFC Near Field Communication drivers of any kind: ${WHITE}"  response  
response=${response,,}
case "$response" in 
   [yY])  echo " NoExtract = usr/lib/modules/[1-9]*-ARCH/kernel/drivers/nfc* usr/lib/modules/[1-9]*-ARCH/kernel/net/nfc* " >> /etc/pacman.d/tuned.conf ;;
   ?) echo ${RED} "declined" "${WHITE}" ;;
esac

read -rp "${BLUE} Apple Mac Thunderbolt drivers of any kind: ${WHITE}"  response  
response=${response,,}
case "$response" in 
   [yY])  echo " NoExtract = usr/lib/modules/[1-9]*-ARCH/kernel/drivers/thunderbolt* " >> /etc/pacman.d/tuned.conf ;;
   ?) echo ${RED} "declined" "${WHITE}" ;;
esac

read -rp "${BLUE} PCMCIA Notebook pluggable card drivers of any kind from year 1990 or older: ${WHITE}"  response  
response=${response,,}
case "$response" in 
   [yY])  echo " NoExtract = usr/lib/modules/[1-9]*-ARCH/kernel/drivers/pcmcia* " >> /etc/pacman.d/tuned.conf ;;
   ?) echo ${RED} "declined" "${WHITE}" ;;
esac

read -rp "${BLUE} HAM Radio Hobby radio drivers of any kind: ${WHITE}"  response  
response=${response,,}
case "$response" in 
   [yY])  echo " NoExtract =  usr/lib/modules/[1-9]*-ARCH/kernel/drivers/net/hamradio* " >> /etc/pacman.d/tuned.conf ;;
   ?) echo ${RED} "declined" "${WHITE}" ;;
esac
read -rp "${BLUE}  WiMax wireless drivers of any kind: ${WHITE}"  response  
response=${response,,}
case "$response" in 
   [yY])  echo " NoExtract = usr/lib/modules/[1-9]*-ARCH/kernel/drivers/net/wimax* usr/lib/modules/[1-9]*-ARCH/kernel/net/wimax*
 " >> /etc/pacman.d/tuned.conf ;;
   ?) echo "${RED}" "declined" "${WHITE}" ;;
esac

read -rp "${BLUE}${BLUE} FireWire drivers: ${WHITE} "  response  
response=${response,,}
case "$response" in 
   [yY])  echo " NoExtract = usr/lib/modules/[1-9]*-ARCH/kernel/drivers/firewire* usr/lib/modules/[1-9]*-ARCH/kernel/drivers/infiniband*
 " >> /etc/pacman.d/tuned.conf ;;
   ?) echo "${RED}" "declined" "${WHITE}" ;;
esac 
 # InfiniBand router and modem drivers:
read -rp "${BLUE} CDROM optical drive drivers: ${WHITE}"  response  
response=${response,,}
case "$response" in 
   [yY])  echo " NoExtract = usr/lib/modules/[1-9]*-ARCH/kernel/drivers/cdrom*
 
 " >> /etc/pacman.d/tuned.conf ;;
   ?) echo "${RED}" "declined" "${WHITE}" ;;
esac
}

sysctl 
echo "${BLUE}" ""
pacman 

exit $?
